development: &development
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  adapter: postgresql
  pool: 30

test:
  <<: *development

staging:
  <<: *development

production:
  <<: *development

